---
name: Test PR

on: [pull_request] # yamllint disable-line rule:truthy

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - LILYGO-T-Higrow-ESP32.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/yamllint.yml
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v5.0.0
        with:
          yaml_file: ${{ matrix.file }}
